sudo: required
services:
  - docker

before_install:
  - docker build -t theodosis1989/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true theodosis1989/react-test npm test

after_success:
  - docker build -t theodosis1989/multi-client ./client
  - docker build -t theodosis1989/multi-nginx ./nginx
  - docker build -t theodosis1989/multi-server ./server
  - docker build -t theodosis1989/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push theodosis1989/multi-client
  - docker push theodosis1989/multi-nginx
  - docker push theodosis1989/multi-server
  - docker push theodosis1989/multi-worker
